#!/bin/sh

renice -1 --pid $$ >/dev/null 2>&1

aprdir='/tmp/ApRoam'
ADDRESS='192.168.1.4'
SURPORT='777'
PORT='702'

mkdir -p $aprdir/ap2

while true
do
        if [ ! -f "$aprdir/ap2/survey.lock" ]; then
		# Launch Server To Receive Survey Data.
		nc -l -p $PORT > $aprdir/ap2/survey.dump 2>/dev/null &
		pid=$!
		echo $pid > /var/run/ApRoamSur2_nc.pid
		# Trigger Access Point To Send Survey Data.
		nc -q0 $ADDRESS $SURPORT 2>/dev/null
                loop=1
                while [ "${loop}" -eq "1" ]
                do
			# Check For Station Lock Kill Server If Running.
                        if [ -f "$aprdir/ap2/survey.lock" ]; then
				kill $pid >/dev/null 2>&1
				loop=0
				# Delay Retreiving Survey Data.
				sleep 8
			else
				sleep .1
			fi
		done
	fi
	sleep .1
done
