#!/bin/sh

renice -1 --pid $$ >/dev/null 2>&1

aprdir='/tmp/ApRoam'
PORT='401'

mkdir -p $aprdir/AP1

while true
do
        if [ ! -f "$aprdir/AP1/network.lock" ]; then
		nc -l -p $PORT > $aprdir/AP1/AP1_network.dump 2>/dev/null &
		pid=$!
		echo $pid > /var/run/ApRoamSrv1_nc.pid
                loop=1
                while [ "$loop" -eq "1" ]
                do
			dumpsize=`stat --printf="%s" $aprdir/AP1/AP1_network.dump`
                        if [ -f "$aprdir/AP1/network.lock" -o "$dumpsize" -gt "25600000" ]; then
				kill $pid >/dev/null 2>&1
				loop=0
			else
				sleep .1
			fi
		done
	fi
	sleep .1
done
