#!/bin/sh

renice -1 --pid $$ >/dev/null 2>&1

aprdir='/tmp/ApRoam'
ADDRESS=$1
PORT=$2
AP=$3
DELAY=$4
STAPORT='666'

mkdir -p $aprdir/$AP

# Delay Retreiving Station Data.
sleep $(($DELAY-2))

# Launch Server To Receive Station Data.
nc -l -p $PORT > $aprdir/$AP/station.dump 2>/dev/null &
pid=$!

# Trigger Access Point To Send Station Data.
nc -q0 -w1 $ADDRESS $STAPORT 2>/dev/null
ERROR=$?
if [ "$ERROR" -gt "0" ]; then
	kill $pid >/dev/null 2>&1
fi

exit 0
