#!/bin/sh

renice -1 --pid $$ >/dev/null 2>&1

aprdir='/tmp/ApRoam'
ADDRESS='192.168.1.6'
STAPORT='666'
PORT='603'

mkdir -p $aprdir/ap3

while true
do
        if [ ! -f "$aprdir/ap3/station.lock" ]; then
		# Launch Server To Receive Station Data.
		nc -l -p $PORT > $aprdir/ap3/station.dump 2>/dev/null &
		pid=$!
		echo $pid > /var/run/ApRoamSta3_nc.pid
		# Trigger Access Point To Send Station Data.
		nc -q0 $ADDRESS $STAPORT 2>/dev/null
                loop=1
                while [ "${loop}" -eq "1" ]
                do
			# Check For Station Lock Kill Server If Running.
                        if [ -f "$aprdir/ap3/station.lock" ]; then
				kill $pid >/dev/null 2>&1
				loop=0
				# Delay Retreiving Station Data.
				sleep 8
			else
				sleep .1
			fi
		done
	fi
	sleep .1
done
