#!/bin/sh

renice -1 --pid $$ >/dev/null 2>&1

aprdir='/tmp/ApRoam'
PORT='603'

mkdir -p $aprdir/ap3

while true
do
        if [ ! -f "$aprdir/ap3/station.lock" ]; then
		nc -l -p $PORT > $aprdir/ap3/station.dump 2>/dev/null &
		pid=$!
		echo $pid > /var/run/ApRoamSta3_nc.pid
                loop=1
                while [ "${loop}" -eq "1" ]
                do
                        if [ -f "$aprdir/ap3/station.lock" ]; then
				kill $pid >/dev/null 2>&1
				loop=0
			else
				sleep .1
			fi
		done
	fi
	sleep .1
done
