#!/bin/sh

# Block client from reconnecting.
ebtables -A FORWARD -s $1 -j DROP
ebtables -A INPUT -s $1 -j DROP
# Kick client from access point by deauthenticating it.
hostapd_cli -i wlan0 deauthenticate $1
# Keep client from reconnecting for 10 seconds.
sleep 10
# Allow client to reconnect.
ebtables -D FORWARD -s $1 -j DROP
ebtables -D INPUT -s $1 -j DROP
exit 0
