#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=99

APP=ApRoamDeauth
PID_FILE=/var/run/ApRoamDeauth.pid

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

boot() {
	service_start /usr/local/bin/ApRoamDeauth
}


start() {
	service_start /usr/local/bin/ApRoamDeauth
}

stop() {
	start-stop-daemon -K -n $APP -p $PID_FILE -s TERM
	rm -rf $PID_FILE
	pid=`cat /var/run/deauth_nc.pid`
	kill $pid
}
