#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=99

APP=ApRoamSta
PID_FILE=/var/run/ApRoamSta.pid

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

boot() {
	service_start /usr/local/bin/ApRoamSta
}


start() {
	service_start /usr/local/bin/ApRoamSta
}

stop() {
	start-stop-daemon -K -n $APP -p $PID_FILE -s TERM
	rm -rf $PID_FILE
}
