#!/bin/sh

renice -1 $$ >/dev/null 2>&1

#### Paths. ####

aprdir='/tmp/ApRoam'
controllog='control.log'
deauthlog='deauth.log'
logdir='/var/log/ApRoam'

#### SIGNAL PROCESSING FUNCTION ####

sig_proc() {
	# On the ap the station is currently connected to calculate the snr difference between now and the previously detected snr.
	if [ -f $aprdir/${2}snr.$1 ]; then
		PREVSNR=`cat $aprdir/${2}snr.$1`
		SNR=$3
		if [ "$SNR" -lt "$PREVSNR" ]; then
			SNRDIFF=$(($PREVSNR-$SNR))
		else
			SNRDIFF=0
		fi
	else
		SNRDIFF=0
	fi
	# On the ap the station is currently recieving a stronger snr calculate the snr difference between now and the previously detected snr.
        if [ -f $aprdir/${4}snr.$1 ]; then
		PREVSNR2=`cat $aprdir/${4}snr.$1`
                SNR2=$5
                if [ "$SNR2" -gt "$PREVSNR2" -a "$PREVSNR2" -ne "0" ]; then
                        SNR2DIFF=$(($SNR2-$PREVSNR2))
                else
                        SNR2DIFF=0
                fi
        else
                SNR2DIFF=0
        fi
	# Check the snr difference if it was large it might have been a bad signal so don't deauthenticate and reduce the current snr by five.
	# Otherwise deauthenticate.
	if [ "$SNRDIFF" -lt "$MAXSNRDIFF" -a "$SNR2DIFF" -lt "$MAXSNRDIFF" ]; then
		DEAUTHSTATION=1
	else
		if [ "$SNRDIFF" -ge "$MAXSNRDIFF" ]; then
			SNR=$((${SNR}+5))
		fi
		if [ "$SNR2DIFF" -ge "$MAXSNRDIFF" ]; then
			SNR2=$((${SNR2}-5))
		fi
		# The snr difference was large so ignore it and don't deauthenticate.
		DEAUTHSTATION=0
	fi
}

#### INTIALIZE VARIABLES AND CLEAN UP. ####

AP1ADDRESS='192.168.1.2'
AP2ADDRESS='192.168.1.4'
AP3ADDRESS='192.168.1.8'
DEAUTHPORT='555'
DEAUTHSTATION='1'
DEFAULTNOISE='-88'
KEEPALIVELOOP='10'
MAXSNR='70'
MAXSNRDIFF='20'
# KEEPALIVE sets how often you ping stations. Pinging improves signal detection but at the cost of increased battery consumption by the stations.
# To set KEEPALIVE: 0=Ping disabled 10=Ping every 10 seconds 20=Ping every 20 seconds 30=Ping every 30 seconds etc.
KEEPALIVE='10'
rm -f $aprdir/ap*snr.*
rm -f $aprdir/ap*prevnoise
rm -f $aprdir/deauth
mkdir -p $aprdir
mkdir -p $logdir
touch $logdir/deauth.log

#### MAIN LOOP ####

while true
do
	STARTTIME=`date +%s`
	DATE=`date`
	echo "-------------------- $DATE --------------------" >> $logdir/$controllog

	#### RETREIVE STATION AND SURVEY DATA. ####

	### AP1 ###
	touch $aprdir/ap1/survey.lock >/dev/null 2>&1
	touch $aprdir/ap1/station.lock >/dev/null 2>&1
	sleep .15
	## Retreive Access Point 1 Survey Dump. ##
	AP1NOISE=`grep -A1 'in use' $aprdir/ap1/survey.dump 2>/dev/null | grep noise: | awk '{print $2}'`
	if [ "$AP1NOISE" = "" ]; then
		if [ -f $aprdir/ap1prevnoise ]; then
			AP1NOISE=`cat $aprdir/ap1prevnoise`
		else
			AP1NOISE=$DEFAULTNOISE
		fi
	else
		echo $AP1NOISE > $aprdir/ap1prevnoise
	fi
	rm -f $aprdir/ap1/survey.lock >/dev/null 2>&1
	rm -f $aprdir/ap1/survey.dump >/dev/null 2>&1
	## Retreive Access Point 1 Station Dump. ##
	AP1STATIONS=`grep "Station" $aprdir/ap1/station.dump 2>/dev/null | awk '{print $2}'`
        rm -f $aprdir/ap1/station.lock >/dev/null 2>&1
	rm -f $aprdir/ap1/station.dump >/dev/null 2>&1

	### AP2 ###
        touch $aprdir/ap2/survey.lock >/dev/null 2>&1
	touch $aprdir/ap2/station.lock >/dev/null 2>&1
	sleep .15
	## Retreive Access Point 2 Survey Dump. ##
	AP2NOISE=`grep -A1 'in use' $aprdir/ap2/survey.dump 2>/dev/null | grep noise: | awk '{print $2}'`
	if [ "$AP2NOISE" = "" ]; then
		if [ -f $aprdir/ap2prevnoise ]; then
			AP2NOISE=`cat $aprdir/ap2prevnoise`
		else
			AP2NOISE=$DEFAULTNOISE
		fi
	else
		echo $AP2NOISE > $aprdir/ap2prevnoise
	fi
	rm -f $aprdir/ap2/survey.lock >/dev/null 2>&1
	rm -f $aprdir/ap2/survey.dump >/dev/null 2>&1
	## Retreive Access Point 2 Station Dump. ##
        AP2STATIONS=`grep "Station" $aprdir/ap2/station.dump 2>/dev/null | awk '{print $2}'`
        rm -f $aprdir/ap2/station.lock >/dev/null 2>&1
	rm -f $aprdir/ap2/station.dump >/dev/null 2>&1

	### AP3 ###
	touch $aprdir/ap3/survey.lock >/dev/null 2>&1
	touch $aprdir/ap3/station.lock >/dev/null 2>&1
	sleep .15
	## Retreive Access Point 3 Survey Dump. ##
	AP3NOISE=`grep -A1 'in use' $aprdir/ap3/survey.dump 2>/dev/null | grep noise: | awk '{print $2}'`
	if [ "$AP3NOISE" = "" ]; then
		if [ -f $aprdir/ap3prevnoise ]; then
			AP3NOISE=`cat $aprdir/ap3prevnoise`
		else
			AP3NOISE=$DEFAULTNOISE
		fi
	else
		echo $AP3NOISE > $aprdir/ap3prevnoise
	fi
	rm -f $aprdir/ap3/survey.lock >/dev/null 2>&1
	rm -f $aprdir/ap3/survey.dump >/dev/null 2>&1
	## Retreive Access Point 3 Station Dump. ##
        AP3STATIONS=`grep "Station" $aprdir/ap3/station.dump 2>/dev/null | awk '{print $2}'`
        rm -f $aprdir/ap3/station.lock >/dev/null 2>&1
	rm -f $aprdir/ap3/station.dump >/dev/null 2>&1

	# Combine All Access Point Clients.
	STATIONS="$AP1STATIONS $AP2STATIONS $AP3STATIONS"

	# Strip Out Duplicates.
	STATIONS=`echo "$STATIONS" | grep -Eo ..\(\:..\){5} | awk '!a[$0]++'`

	# Get Station Count.
	STATIONCOUNT=`echo "$STATIONS" | grep -Eoc ..\(\:..\){5}`

	#### PING STATIONS TO IMPROVE CHANCE OF RETREIVING A SIGNAL. ####
	if [ "$KEEPALIVELOOP" -ge "$KEEPALIVE" -a "$KEEPALIVE" -ne "0" ]; then
		KEEPALIVELOOP=10
		COUNT=$STATIONCOUNT
		while [ "$COUNT" -gt "0" ]
		do
			STATION=`echo $STATIONS | awk -v x=$COUNT '{print $x}'`
			# First Try Retreiving Ip Address From Dnsmasq Lease File.
			ip=`cat /var/lib/misc/dnsmasq.leases | grep -m1 "$STATION" | awk '{print $3}'`
			if [ "$ip" = "" ]; then
				# Second Try Retreiving Ip Address From Arp Cache.
				ip=`cat /proc/net/arp | grep -m1 "$STATION" | awk '{print $1}'`
				if [ "$ip" = "" ]; then
					# Third Try Pinging Every Ip Address On Subnet.
					fping -b1 -c1 -i1 -q -r0 -t1 -g 192.168.1.0/24 >/dev/null 2>&1
					COUNT=0
				else
					ping -i .05 -c 1 -s 0 $ip >/dev/null 2>&1 &
				fi
			else
				ping -i .05 -c 1 -s 0 $ip >/dev/null 2>&1 &
			fi
			COUNT=$(($COUNT-1))
		done
	elif [ "$KEEPALIVE" -eq "0" ]; then
		KEEPALIVELOOP=10
	else
		KEEPALIVELOOP=$(($KEEPALIVELOOP+10))
	fi

	#### RETREIVE NETWORK DATA AND DO PREPROCESSING. ####

        # Retreive Access Point 1 Network Data Dump.
	touch $aprdir/ap1/network.lock >/dev/null 2>&1
	sleep .15
	# Preprocess Network Data By Greping Out Unwanted Packets.
	tcpdump -e -t -r $aprdir/ap1/ap1_network.dump 2>/dev/null | grep -E -v 'Acknowledgment|Beacon|Broadcast|Data' | grep -v "(oui Unknown) BA" > $aprdir/ap1_network.dump
	rm -f $aprdir/ap1/network.lock >/dev/null 2>&1

        # Retreive Access Point 2 Network Data Dump.
	touch $aprdir/ap2/network.lock >/dev/null 2>&1
	sleep .15
	# Preprocess Network Data By Greping Out Unwanted Packets.
	tcpdump -e -t -r $aprdir/ap2/ap2_network.dump 2>/dev/null | grep -E -v 'Acknowledgment|Beacon|Broadcast|Data' | grep -v "(oui Unknown) BA" > $aprdir/ap2_network.dump
	rm -f $aprdir/ap2/network.lock >/dev/null 2>&1

	# Retreive Access Point 3 Network Data Dump.
	touch $aprdir/ap3/network.lock >/dev/null 2>&1
	sleep .15
	# Preprocess Network Data By Greping Out Unwanted Packets.
	tcpdump -e -t -r $aprdir/ap3/ap3_network.dump 2>/dev/null | grep -E -v 'Acknowledgment|Beacon|Broadcast|Data' | grep -v "(oui Unknown) BA" > $aprdir/ap3_network.dump
	rm -f $aprdir/ap3/network.lock >/dev/null 2>&1

	#### RETREIVE STATION SIGNAL VALUES. ####

	while [ "${STATIONCOUNT}" -gt "0" ]
	do
		APSNRDIFF='0'
		DEAUTHSTATION='0'
		SNRDIFF='0'
		SNR2DIFF='0'
		STATION=`echo $STATIONS | awk -v x=$STATIONCOUNT '{print $x}'`
		CONNECTEDTOAP1=`echo $AP1STATIONS | grep -c $STATION`
		CONNECTEDTOAP2=`echo $AP2STATIONS | grep -c $STATION`
		CONNECTEDTOAP3=`echo $AP3STATIONS | grep -c $STATION`

		AP1SIGNAL=`grep $STATION $aprdir/ap1_network.dump 2>/dev/null | grep -E -o "\-[0-9]{1,2}dB" | cut -d 'd' -f1  | tail -1`
		if [ "$AP1SIGNAL" = "" ]; then
			AP1SNR=0
		elif [ "$AP1SIGNAL" -le "$AP1NOISE" ]; then
			AP1SNR=0
		else
			AP1SNR=`echo $(($AP1NOISE-$AP1SIGNAL)) | sed 's/-//'`
		fi
		AP2SIGNAL=`grep $STATION $aprdir/ap2_network.dump 2>/dev/null | grep -E -o "\-[0-9]{1,2}dB" | cut -d 'd' -f1  | tail -1`
		if [ "$AP2SIGNAL" = "" ]; then
			AP2SNR=0
                elif [ "$AP2SIGNAL" -le "$AP2NOISE" ]; then
			AP2SNR=0
		else
                        AP2SNR=`echo $(($AP2NOISE-$AP2SIGNAL)) | sed 's/-//'`
                fi
		AP3SIGNAL=`grep $STATION $aprdir/ap3_network.dump 2>/dev/null | grep -E -o "\-[0-9]{1,2}dB" | cut -d 'd' -f1  | tail -1`
		if [ "$AP3SIGNAL" = "" ]; then
			AP3SNR=0
		elif [ "$AP3SIGNAL" -le "$AP3NOISE" ]; then
			AP3SNR=0
		else
                        AP3SNR=`echo $(($AP3NOISE-$AP3SIGNAL)) | sed 's/-//'`
		fi

		#### PREVENT STATIONS FROM CONSTANTLY HOPPING AROUND DIFFERENT ACCESS POINTS DO TO SIMULAR SIGNAL TO NOISE LEVELS. ####

		ADJUST=0
		if [ "$CONNECTEDTOAP1" -gt "0" ]; then
			if [ "${AP1SNR}" -lt "${AP2SNR}" -o "${AP1SNR}" -lt "${AP3SNR}" ]; then
				if [ "${AP1SNR}" -ge "35" ]; then
					ADJUST=99
				elif [ "${AP1SNR}" -ge "30" ]; then
					ADJUST=18
                        	elif [ "${AP1SNR}" -ge "25" ]; then
					ADJUST=15
				elif [ "${AP1SNR}" -ge "20" ]; then
					ADJUST=10
				elif [ "${AP1SNR}" -gt "0" ]; then
					ADJUST=8
				fi
			fi
		fi
		if [ "$CONNECTEDTOAP2" -gt "0" ]; then
			if [ "${AP2SNR}" -lt "${AP1SNR}" -o "${AP2SNR}" -lt "${AP3SNR}" ]; then
				if [ "${AP2SNR}" -ge "35" ]; then
					ADJUST=99
				elif [ "${AP2SNR}" -ge "30" ]; then
					ADJUST=18
				elif [ "${AP2SNR}" -ge "25" ]; then
					ADJUST=15
				elif [ "${AP2SNR}" -ge "20" ]; then
					ADJUST=10
				elif [ "${AP2SNR}" -gt "0" ]; then
					ADJUST=8
				fi
			fi
		fi
		if [ "$CONNECTEDTOAP3" -gt "0" ]; then
			if [ "${AP3SNR}" -lt "${AP1SNR}" -o "${AP3SNR}" -lt "${AP2SNR}" ]; then
				if [ "${AP3SNR}" -ge "35" ]; then
					ADJUST=99
				elif [ "${AP3SNR}" -ge "30" ]; then
					ADJUST=18
				elif [ "${AP3SNR}" -ge "25" ]; then
					ADJUST=15
				elif [ "${AP3SNR}" -ge "20" ]; then
					ADJUST=10
				elif [ "${AP3SNR}" -gt "0" ]; then
					ADJUST=8
				fi
			fi
		fi

		#### LOG. ####

		echo " " >> $logdir/$controllog
		echo "STATION = $STATION" >> $logdir/$controllog
		echo "AP1 SNR = $AP1SNR dBm" >> $logdir/$controllog
		echo "AP2 SNR = $AP2SNR dBm">> $logdir/$controllog
		echo "AP3 SNR = $AP3SNR dBm" >> $logdir/$controllog

		if [ "$CONNECTEDTOAP1" -gt "0" ]; then
			echo "CONNECTED TO = AP1" >> $logdir/$controllog
		elif [ "$CONNECTEDTOAP2" -gt "0" ]; then
			echo "CONNECTED TO = AP2" >> $logdir/$controllog
		elif [ "$CONNECTEDTOAP3" -gt "0" ]; then
			echo "CONNECTED TO = AP3" >> $logdir/$controllog
		fi

		#### COMPARE SIGNAL LEVELS WITH OTHER ACCESS POINTS AND SEND DEAUTHENTICATION TO STATION IF ANOTHER ACCESS POINT HAS A BETTER SIGNAL. ####

		if [ "$CONNECTEDTOAP1" -gt "0" ]; then
			if [ "${AP2SNR}" -gt "$(($AP1SNR+$ADJUST))" -a "${AP2SNR}" -ne "0" -a "${AP1SNR}" -ne "0" ]; then
				if [ "${AP2SNR}" -le "${MAXSNR}" ]; then
					APSNRDIFF=$(($AP2SNR-$AP1SNR))
					sig_proc "$STATION" ap1 $AP1SNR ap2 $AP2SNR
					if [ "$DEAUTHSTATION" -eq "1" ]; then
						echo "AP1          = DEAUTHENTICATING!" >> $logdir/$controllog
						echo "$STATION" | nc -q0 $AP1ADDRESS $DEAUTHPORT 2>/dev/null &
					fi
					if [ "$AP1SNR" -ne "$SNR" ]; then
						AP1SNR=$SNR
						echo "AP1 ADJUSTED SNR  = $AP1SNR dBm" >> $logdir/$controllog
					fi
					if [ "$AP2SNR" -ne "$SNR2" ]; then
						AP2SNR=$SNR2
						echo "AP2 ADJUSTED SNR  = $AP2SNR dBm" >> $logdir/$controllog
					fi
				else
					echo "AP2 MAX SNR  = $AP2SNR dBm EXCEEDES THE MAX $MAXSNR dBm ALLOWED NOT DEAUTHENTICATING!" >> $logdir/$controllog
				fi
			elif [ "${AP3SNR}" -gt "$(($AP1SNR+$ADJUST))" -a "${AP3SNR}" -ne "0" -a "${AP1SNR}" -ne "0" ]; then
				if [ "${AP3SNR}" -le "${MAXSNR}" ]; then
					APSNRDIFF=$(($AP3SNR-$AP1SNR))
					sig_proc "$STATION" ap1 $AP1SNR ap3 $AP3SNR
					if [ "$DEAUTHSTATION" -eq "1" ]; then
						echo "AP1          = DEAUTHENTICATING!" >> $logdir/$controllog
						echo "$STATION" | nc -q0 $AP1ADDRESS $DEAUTHPORT 2>/dev/null &
					fi
                                	if [ "$AP1SNR" -ne "$SNR" ]; then
                                        	AP1SNR=$SNR
                                        	echo "AP1 ADJUSTED SNR  = $AP1SNR dBm" >> $logdir/$controllog
                                	fi
                                	if [ "$AP3SNR" -ne "$SNR2" ]; then
                                        	AP3SNR=$SNR2
                                        	echo "AP3 ADJUSTED SNR  = $AP3SNR dBm" >> $logdir/$controllog
                                	fi
				else
					echo "AP3 MAX SNR  = $AP3SNR dBm EXCEEDES THE MAX $MAXSNR dBm ALLOWED NOT DEAUTHENTICATING!" >> $logdir/$controllog
				fi
			fi
		fi
		if [ "$CONNECTEDTOAP2" -gt "0" ]; then
                        if [ "${AP1SNR}" -gt "$(($AP2SNR+$ADJUST))" -a "${AP1SNR}" -ne "0" -a "${AP2SNR}" -ne "0" ]; then
				if [ "${AP1SNR}" -le "${MAXSNR}" ]; then
					APSNRDIFF=$(($AP1SNR-$AP2SNR))
					sig_proc "$STATION" ap2 $AP2SNR ap1 $AP1SNR
					if [ "$DEAUTHSTATION" -eq "1" ]; then
                                		echo "AP2          = DEAUTHENTICATING!" >> $logdir/$controllog
                                		echo "$STATION" | nc -q0 $AP2ADDRESS $DEAUTHPORT 2>/dev/null &
					fi
                                	if [ "$AP2SNR" -ne "$SNR" ]; then
                                        	AP2SNR=$SNR
                                        	echo "AP2 ADJUSTED SNR  = $AP2SNR dBm" >> $logdir/$controllog
                                	fi
                                	if [ "$AP1SNR" -ne "$SNR2" ]; then
                                        	AP1SNR=$SNR2
                                        	echo "AP1 ADJUSTED SNR  = $AP1SNR dBm" >> $logdir/$controllog
                                	fi
				else
					echo "AP1 MAX SNR  = $AP1SNR dBm EXCEEDES THE MAX $MAXSNR dBm ALLOWED NOT DEAUTHENTICATING!" >> $logdir/$controllog
				fi
                        elif [ "${AP3SNR}" -gt "$(($AP2SNR+$ADJUST))" -a "${AP3SNR}" -ne "0" -a "${AP2SNR}" -ne "0" ]; then
				if [ "${AP3SNR}" -le "${MAXSNR}" ]; then
					APSNRDIFF=$(($AP3SNR-$AP2SNR))
					sig_proc "$STATION" ap2 $AP2SNR ap3 $AP3SNR
					if [ "$DEAUTHSTATION" -eq "1" ]; then
                                		echo "AP2          = DEAUTHENTICATING!" >> $logdir/$controllog
                                		echo "$STATION" | nc -q0 $AP2ADDRESS $DEAUTHPORT 2>/dev/null &
					fi
                                	if [ "$AP2SNR" -ne "$SNR" ]; then
                                        	AP2SNR=$SNR
                                        	echo "AP ADJUSTED SNR  = $AP2SNR dBm " >> $logdir/$controllog
                                	fi
                                	if [ "$AP3SNR" -ne "$SNR2" ]; then
                                        	AP3SNR=$SNR2
                                        	echo "AP3 ADJUSTED SNR  = $AP3SNR dBm" >> $logdir/$controllog
                                	fi
				else
					echo "AP3 MAX SNR  = $AP3SNR dBm EXCEEDES THE MAX $MAXSNR dBm ALLOWED NOT DEAUTHENTICATING!" >> $logdir/$controllog
				fi
                        fi
                fi
		if [ "$CONNECTEDTOAP3" -gt "0" ]; then
                        if [ "${AP1SNR}" -gt "$(($AP3SNR+$ADJUST))" -a "${AP1SNR}" -ne "0" -a "${AP3SNR}" -ne "0" ]; then
				if [ "${AP1SNR}" -le "${MAXSNR}" ]; then
					APSNRDIFF=$(($AP1SNR-$AP3SNR))
					sig_proc "$STATION" ap3 $AP3SNR ap1 $AP1SNR
					if [ "$DEAUTHSTATION" -eq "1" ]; then
						echo "AP3          = DEAUTHENTICATING!" >> $logdir/$controllog
						echo "$STATION" | nc -q0 $AP3ADDRESS $DEAUTHPORT 2>/dev/null &
					fi
                                	if [ "$AP3SNR" -ne "$SNR" ]; then
                                        	AP3SNR=$SNR
                                        	echo "AP3 ADJUSTED SNR  = $AP3SNR dBm" >> $logdir/$controllog
                                	fi
                                	if [ "$AP1SNR" -ne "$SNR2" ]; then
                                        	AP1SNR=$SNR2
                                        	echo "AP1 ADJUSTED SNR  = $AP1SNR dBm" >> $logdir/$controllog
                                	fi
				else
					echo "AP1 MAX SNR  = $AP1SNR dBm EXCEEDES THE MAX $MAXSNR dBm ALLOWED NOT DEAUTHENTICATING!" >> $logdir/$controllog
				fi
                        elif [ "${AP2SNR}" -gt "$(($AP3SNR+$ADJUST))" -a "${AP2SNR}" -ne "0" -a "${AP3SNR}" -ne "0" ]; then
				if [ "${AP2SNR}" -le "${MAXSNR}" ]; then
					APSNRDIFF=$(($AP2SNR-$AP3SNR))
					sig_proc "$STATION" ap3 $AP3SNR ap2 $AP2SNR
					if [ "$DEAUTHSTATION" -eq "1" ]; then
						echo "AP3          = DEAUTHENTICATING!" >> $logdir/$controllog
						echo "$STATION" | nc -q0 $AP3ADDRESS $DEAUTHPORT 2>/dev/null &
					fi
                                	if [ "$AP3SNR" -ne "$SNR" ]; then
                                        	AP3SNR=$SNR
                                        	echo "AP3 ADJUSTED SNR  = $AP3SNR dBm" >> $logdir/$controllog
                                	fi
                                	if [ "$AP2SNR" -ne "$SNR2" ]; then
                                        	AP2SNR=$SNR2
                                        	echo "AP2 ADJUSTED SNR  = $AP2SNR dBm" >> $logdir/$controllog
                                	fi
				else
					echo "AP2 MAX SNR  = $AP2SNR dBm EXCEEDES THE MAX $MAXSNR dBm ALLOWED NOT DEAUTHENTICATING!" >> $logdir/$controllog
                        	fi
			fi
		fi

		#### LOG. ####

		if [ "$DEAUTHSTATION" -eq "1" ]; then
			if [ "$CONNECTEDTOAP1" -gt "0" ]; then
				AP='AP1'
			elif [ "$CONNECTEDTOAP2" -gt "0" ]; then
				AP='AP2'
			else
				AP='AP3'
			fi
			DATE=`date`
			echo "-------------------- $DATE --------------------" >> $logdir/$deauthlog
			echo " " >> $logdir/$deauthlog
			echo "STATION = $STATION\nCONNECTED AP = $AP\nAPSNRDIFF    = $APSNRDIFF dBm\nADJUST       = $ADJUST dBm\nAP1 = $AP1SNR dBm\nAP2 = $AP2SNR dBm\nAP3 = $AP3SNR dBm \
			\nAP MAX CUR TO PREV SNR DIFF  = $MAXSNRDIFF dBm\nAP CUR TO PREV SNR DIFF      = $SNRDIFF dBm\nNEW AP CUR TO PREV SNR DIFF  = $SNR2DIFF dBm\n" >> $logdir/$deauthlog
			echo "----------------------------------------------------------------------" >> $logdir/$deauthlog
			echo " " >> $logdir/$deauthlog
		fi

		if [ "$APSNRDIFF" -gt "0" ]; then
			echo "ACCESS POINT SNR DIFF         = $APSNRDIFF dBm" >> $logdir/$controllog
		fi
		if [ "$ADJUST" -gt "0" ]; then
			echo "SNR THRESHOLD                 = $ADJUST dBm" >> $logdir/$controllog
		fi
		if [ "$SNRDIFF" -gt "0" ]; then
				echo "AP CUR TO PREV SNR DIFF       = $SNRDIFF dBm" >> $logdir/$controllog
		fi
		if [ "$SNR2DIFF" -gt "0" ]; then
				echo "NEW AP CUR TO PREV SNR DIFF   = $SNR2DIFF dBm" >> $logdir/$controllog
		fi
		if [ "$SNRDIFF" -ge "$MAXSNRDIFF" -o "$SNR2DIFF" -ge "$MAXSNRDIFF" ]; then
			echo "AP MAX CUR TO PREV SNR DIFF   = $MAXSNRDIFF dBm EXCEEDED! NOT DEAUTHENTICATING!" >> $logdir/$controllog
		fi


		#### SAVE CURRENT STATION SNR FOR ALL ACCESS POINTS. ####

		if [ "$AP1SNR" -ne "0" ]; then
			echo $AP1SNR > $aprdir/ap1snr.$STATION
		fi
		if [ "$AP2SNR" -ne "0" ]; then
			echo $AP2SNR > $aprdir/ap2snr.$STATION
		fi
		if [ "$AP3SNR" -ne "0" ]; then
			echo $AP3SNR > $aprdir/ap3snr.$STATION
		fi

		STATIONCOUNT=$(($STATIONCOUNT-1))
	done

	#### LOG. ####

	echo " " >> $logdir/$controllog
	DATE=`date`
        echo "-------------------- $DATE --------------------" >> $logdir/$controllog
	echo " " >> $logdir/$controllog

	#### DYNAMICALLY ADJUST SLEEP TIME BASED ON HOW LONG IT TOOK TO EXECUTE.

	ENDTIME=`date +%s`
	EXETIME=$(($ENDTIME-$STARTTIME))
	SLEEPTIME=$((10-$EXETIME))
	if [ "$SLEEPTIME" -gt "0" ]; then
		sleep $SLEEPTIME
	fi
done
