#! /bin/sh
### BEGIN INIT INFO
# Provides:          ApRoamControl
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Access Point Controller Service
# Description:       Debian init script for the access point controller service.
### END INIT INFO
#
# Author:	Harley Peters <harley@biterror.net>
#

PATH=/usr/local/bin:/bin:/usr/bin:/sbin:/usr/sbin
DAEMON=/usr/local/bin/ApRoamControl
PIDFILE=/var/run/ApRoamControl.pid

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

case "$1" in
  start)
	log_daemon_msg "Starting Access Point Roam Controller Service" "ApRoamControl"
	#start_daemon -b -m $PIDFILE $DAEMON
	start-stop-daemon --start -b -m --pidfile $PIDFILE --exec $DAEMON
	log_end_msg $?
    ;;
  stop)
	log_daemon_msg "Stopping Access Point Roam Controller Service" "ApRoamControl"
	killproc -p $PIDFILE $DAEMON
	log_end_msg $?
    ;;
  force-reload|restart)
    $0 stop
    $0 start
    ;;
  status)
    status_of_proc -p $PIDFILE $DAEMON ApRoamControl && exit 0 || exit $?
    ;;
  *)
    echo "Usage: /etc/init.d/ApRoamControl {start|stop|restart|force-reload|status}"
    exit 1
    ;;
esac

exit 0
