#! /bin/sh
### BEGIN INIT INFO
# Provides:          ApRoamTest1
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Access Point 1 Netcat Server Service
# Description:       Debian init script for the access point 1 netcat server service.
### END INIT INFO
#
# Author:	Harley Peters <harley@biterror.net>
#

PATH=/usr/local/bin:/bin:/usr/bin:/sbin:/usr/sbin
DAEMON=/usr/local/bin/ApRoamTest1
PIDFILE=/var/run/ApRoamTest1.pid

#test -x $DAEMON || exit 0

. /lib/lsb/init-functions

case "$1" in
  start)
	log_daemon_msg "Starting Access Point 1 Netcat Server Service" "ApRoamTest1"
	start-stop-daemon --start -b -m --pidfile $PIDFILE --exec $DAEMON
	log_end_msg $?
    ;;
  stop)
	log_daemon_msg "Stopping Access Point 1 Netcat Server Service" "ApRoamTest1"
	killproc -p $PIDFILE $DAEMON
	log_end_msg $?
    ;;
  force-reload|restart)
    $0 stop
    $0 start
    ;;
  status)
    status_of_proc -p $PIDFILE $DAEMON ApRoamTest1 && exit 0 || exit $?
    ;;
  *)
    echo "Usage: /etc/init.d/ApRoamTest1 {start|stop|restart|force-reload|status}"
    exit 1
    ;;
esac

exit 0
