#! /bin/sh
### BEGIN INIT INFO
# Provides:          ApRoamSur1
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Access Point 1 Survey Netcat Server Service
# Description:       Debian init script for the access point 1 survey netcat server service.
### END INIT INFO
#
# Author:	Harley Peters <harley@biterror.net>
#

PATH=/usr/local/bin:/bin:/usr/bin:/sbin:/usr/sbin
NUMBER='1'
NAME="ApRoamSur$NUMBER"
DAEMON=/usr/local/bin/$NAME
PIDFILE=/var/run/$NAME.pid

#test -x $DAEMON || exit 0

. /lib/lsb/init-functions

case "$1" in
  start)
	log_daemon_msg "Starting Access Point $NUMBER Survey Netcat Server Service" "$NAME"
	start-stop-daemon --start -b -m --pidfile $PIDFILE --exec $DAEMON
	log_end_msg $?
    ;;
  stop)
	log_daemon_msg "Stopping Access Point $NUMBER Survey Netcat Server Service" "$NAME"
	killproc -p $PIDFILE $DAEMON
	log_end_msg $?
	log_daemon_msg "Stopping Access Point $NUMBER Survey Netcat Server Service Process" "nc\n"
	pid=`cat /run/${NAME}_nc.pid`
	kill $pid 2>/dev/null
    ;;
  force-reload|restart)
    $0 stop
    $0 start
    ;;
  status)
    status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
    ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload|status}"
    exit 1
    ;;
esac

exit 0
